// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_System;

#nullable disable

namespace University_System.Migrations
{
    [DbContext(typeof(UniversityContext))]
    partial class UniversityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursescourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsstudentId")
                        .HasColumnType("int");

                    b.HasKey("CoursescourseId", "StudentsstudentId");

                    b.HasIndex("StudentsstudentId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("University_System.Models.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseId"));

                    b.Property<string>("courseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("courseTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("creditHours")
                        .HasColumnType("int");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<int?>("instructorId")
                        .HasColumnType("int");

                    b.Property<string>("semesterOffered")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("courseId");

                    b.HasIndex("departmentId");

                    b.HasIndex("instructorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("University_System.Models.Department", b =>
                {
                    b.Property<int>("departmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentId"));

                    b.Property<decimal>("budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("building")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("headInstructorId")
                        .HasColumnType("int");

                    b.HasKey("departmentId");

                    b.HasIndex("headInstructorId")
                        .IsUnique()
                        .HasFilter("[headInstructorId] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("University_System.Models.Enrollment", b =>
                {
                    b.Property<int>("enrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enrollmentId"));

                    b.Property<int?>("courseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("enrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("finalGrade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("studentId")
                        .HasColumnType("int");

                    b.HasKey("enrollmentId");

                    b.HasIndex("courseId");

                    b.HasIndex("studentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("University_System.Models.Instructor", b =>
                {
                    b.Property<int>("instructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("instructorId"));

                    b.Property<string>("academicTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("hireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("officeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("instructorId");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("University_System.Models.Student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentId"));

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("enrollmentYear")
                        .HasColumnType("int");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("gpa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("studentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("University_System.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursescourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_System.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsstudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("University_System.Models.Course", b =>
                {
                    b.HasOne("University_System.Models.Department", "department")
                        .WithMany("Courses")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_System.Models.Instructor", "instructor")
                        .WithMany("Courses")
                        .HasForeignKey("instructorId");

                    b.Navigation("department");

                    b.Navigation("instructor");
                });

            modelBuilder.Entity("University_System.Models.Department", b =>
                {
                    b.HasOne("University_System.Models.Instructor", "instructor")
                        .WithOne("department")
                        .HasForeignKey("University_System.Models.Department", "headInstructorId");

                    b.Navigation("instructor");
                });

            modelBuilder.Entity("University_System.Models.Enrollment", b =>
                {
                    b.HasOne("University_System.Models.Course", "course")
                        .WithMany("Enrollments")
                        .HasForeignKey("courseId");

                    b.HasOne("University_System.Models.Student", "student")
                        .WithMany("Enrollments")
                        .HasForeignKey("studentId");

                    b.Navigation("course");

                    b.Navigation("student");
                });

            modelBuilder.Entity("University_System.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("University_System.Models.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("University_System.Models.Instructor", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("department")
                        .IsRequired();
                });

            modelBuilder.Entity("University_System.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
